### PR TITLE
now page should be showed correctly

### PR DESCRIPTION
**Pull request by SkygridRex**
wtf

### CODE REVIEW

**Comment by SkygridRex** [comment]
@AndreTheGamer Necesito mas privilegios, porque casi todo el mundo es dueño?

**Comment by AndreTheGamer** [comment]
Have you tested this yourself?

**Comment by SkygridRex** [comment]
Nope cause Chrome only show raw code

**Comment by SkygridRex** [comment]
Give me more privileges please

**Comment by AndreTheGamer** [comment]
You need to install a wamp server on your computer to test ".php" scripts.

**Comment by AndreTheGamer** [comment]
Without a web server, chrome will show the "raw" code. Download a web server such as "WAMP" if your on windows or apache if on license. Then add the files and test.

Also, the code works fine for me. I think it does not for you since you are not using a web server to test it. 

Chrome can only show html docs, and only a web server can read/excuted php files.

Next time, please test your PR's -.-

**Comment by SkygridRex** [comment]
Well, but taking about privileges, i cant do nothing Give me write access

**Comment by AndreTheGamer** [comment]
Done.

**Comment by TheKillerTacos** [comment]
ill soon use a website with a cron job, that every 3 days the website will update with this repo, if we update something here, in 3 days the Webserver will update.

**Comment by SkygridRex** [comment]
Tested doesnt affect results

**Comment by AndreTheGamer** [comment]
@SkygridRex  told you! :yum:

**Comment by SkygridRex** [comment]
hahahaha you are funny :yum:

**Pull request closed without merging**
